# Generated by Django 5.2.4 on 2025-11-16 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='competitors',
        ),
        migrations.DeleteModel(
            name='PlayerAnswer',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
