# Generated by Django 5.2.4 on 2025-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_playeranswer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код вікторини'),
        ),
    ]
