# Generated by Django 5.2.4 on 2025-11-23 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_code'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='access_type',
            field=models.CharField(choices=[('open', 'Open'), ('hosted', 'Hosted')], default='open', max_length=10, verbose_name='Тип доступу'),
        ),
        migrations.CreateModel(
            name='HostedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_code', models.CharField(max_length=8, unique=True)),
                ('is_started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='HostedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hosted_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz.hostedgame')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.quizsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hosted_game', 'user')},
            },
        ),
    ]
