# Generated by Django 5.2.4 on 2025-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_access_type_hostedgame_hostedparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedgame',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
