# Generated by Django 5.2.4 on 2025-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_hostedgame_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/%Y/%m/%d/', verbose_name='Зображення відповіді'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/%Y/%m/%d/', verbose_name='Зображення питання'),
        ),
    ]
